site_name: SHMARQL
repo_url: https://github.com/epoz/shmarql
nav:
  - Introduction: index.md
  - Advanced Searching: fizzysearch.md
  - Configuration:
      - List of Configuration Options: configuration.md
      - With existing websites: proxy.md
      - Using other triplestores: endpoints.md
  - Datastories & Charting: datastories.md
